/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function QuestionMark(props) {
  const { nodes, materials } = useGLTF("/question_mark.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials["Question Mark Background"]}
      />
      <mesh
        geometry={nodes.Question_Mark_base.geometry}
        material={materials.Black}
        position={[0, -1.259, 0]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.Black}
        position={[-0.102, -0.264, 0.206]}
      />
      <mesh
        geometry={nodes.Question_Mark_base001.geometry}
        material={materials.Black}
        position={[0.024, -1.259, -0.273]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials.Black}
        position={[0.126, -0.264, -0.067]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
    </group>
  );
}

useGLTF.preload("/question_mark.glb");
