/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function CityScene(props) {
  const { nodes, materials } = useGLTF("/cityscene.glb");
  return (
    <group
      {...props}
      dispose={null}
      position={props.position}
      rotation-y={props.rotationY}
      scale={props.scale}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Gray 3"]}
        position={[3.305, 3.089, -4.888]}
        rotation={[0, -0.434, 0]}
        scale={[1, 1, 9.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials["Gray 4"]}
        position={[3.305, 0, -4.888]}
        rotation={[0, -0.434, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["Gray 4"]}
        position={[3.305, 0, -4.888]}
        rotation={[0, -0.434, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials["Gray 4"]}
        position={[3.305, 0, -4.888]}
        rotation={[0, -0.434, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials["Gray 4"]}
        position={[3.305, -0.509, -4.888]}
        rotation={[0, -0.434, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials["Gray 4"]}
        position={[3.305, 0, -4.888]}
        rotation={[0, -0.434, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials["Gray 4"]}
        position={[3.305, 0, -4.888]}
        rotation={[0, -0.434, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Gray 4"]}
        position={[3.305, 0, -4.888]}
        rotation={[0, -0.434, 0]}
        scale={[1, 1, 0.385]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials["Gray 3"]}
        scale={[2.503, 1, 0.385]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials["Gray 2"]}
        position={[-3.664, 2.385, -11.221]}
        rotation={[0, 0.134, 0]}
        scale={[1, 2.374, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials.Gray}
        position={[-6.026, 1.698, -11.242]}
        rotation={[0, 0.134, 0]}
        scale={[1, 1.688, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials.Gray}
        position={[0.588, 2.674, -12.259]}
        rotation={[0, 0.134, 0]}
        scale={[0.918, 2.624, 0.918]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials["Gray 2"]}
        position={[0.284, 3.621, -14.77]}
        rotation={[0, 0.134, 0]}
        scale={[0.832, 3.51, 0.832]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials["Gray 3"]}
        position={[-1.542, 2.237, -13.755]}
        rotation={[0, 0.134, 0]}
        scale={[0.894, 2.154, 0.894]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials["Gray 3"]}
        position={[-3.706, 3.579, -13.314]}
        rotation={[0, 0.134, 0]}
        scale={[0.86, 3.448, 0.86]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials["Gray 3"]}
        position={[2.411, 4.473, -13.394]}
        rotation={[0, 0.134, 0]}
        scale={[0.747, 4.453, 0.747]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials["Gray 3"]}
        position={[-1.432, 3.439, -11.486]}
        rotation={[0, 0.134, 0]}
        scale={[0.911, 3.429, 0.911]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["Gray 4"]}
        position={[-1.658, 0, -13.566]}
        rotation={[0, 0.086, 0]}
        scale={[6.96, 1, 1.941]}
      />
    </group>
  );
}

useGLTF.preload("/cityscene.glb");
