/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Crate(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/crate.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (props.isActualWorkbenchClicked) {
      const action = actions["Opened"];
      action.reset().fadeIn(0.5).play();
      return () => {
        action.fadeOut(0.5);
      };
    } else {
      const action = actions["Closed"];
      action.reset().fadeIn(0.5).play();
      return () => {
        action.fadeOut(0.5);
      };
    }
  }, [props.isActualWorkbenchClicked]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Box1">
          <mesh
            name="Box1_1"
            geometry={nodes.Box1_1.geometry}
            material={materials["Dark Green"]}
          />
          <mesh
            name="Box1_2"
            geometry={nodes.Box1_2.geometry}
            material={materials["Yellow Glow"]}
          />
          <mesh
            name="Box1_3"
            geometry={nodes.Box1_3.geometry}
            material={materials.Black}
          />
          <mesh
            name="Box1_4"
            geometry={nodes.Box1_4.geometry}
            material={materials["Dark Gray"]}
          />
        </group>
        <group name="Box2">
          <mesh
            name="Box2_1"
            geometry={nodes.Box2_1.geometry}
            material={materials["Dark Green"]}
          />
          <mesh
            name="Box2_2"
            geometry={nodes.Box2_2.geometry}
            material={materials["Yellow Glow"]}
          />
          <mesh
            name="Box2_3"
            geometry={nodes.Box2_3.geometry}
            material={materials.Black}
          />
          <mesh
            name="Box2_4"
            geometry={nodes.Box2_4.geometry}
            material={materials["Dark Gray"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/crate.glb");
