/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, forwardRef } from "react";
import { useGLTF } from "@react-three/drei";

const MiniHand = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("/minifbhand.glb");
  return (
    <group
      {...props}
      ref={ref}
      dispose={null}
      position={props.position}
      rotation-y={props.rotationY}
      scale={props.scale}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Hand.geometry}
        material={materials.Red}
        position={[0.01, -0.019, 0.018]}
        scale={3.253}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Webs.geometry}
        material={materials.Black}
        position={[0.02, 0.257, -0.161]}
        scale={0.036}
      />
    </group>
  );
});

useGLTF.preload("/minifbhand.glb");

export default MiniHand;
