/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function MiniSymb(props) {
  const { nodes, materials } = useGLTF("/symb_body.glb");
  return (
    <group
      {...props}
      dispose={null}
      position={props.position}
      rotation-y={props.rotationY}
      scale={props.scale}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Spider-Manmesh001"].geometry}
        material={materials.Black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Spider-Manmesh001_1"].geometry}
        material={materials.White}
      />
    </group>
  );
}

useGLTF.preload("/symb_body.glb");
