/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function MiniSpid(props) {
  const { nodes, materials } = useGLTF("/minifbspid.glb");
  return (
    <group {...props} dispose={null} position={[-2.9, 1, 3.27]} scale={0.1}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
      />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Spider-Man_Redmesh"].geometry}
          material={materials.Red}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Spider-Man_Redmesh_1"].geometry}
          material={materials.Blue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Spider-Man_Redmesh_2"].geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Spider-Man_Redmesh_3"].geometry}
          material={materials.White}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/minifbspid.glb");
