/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function MiniSpid(props) {
  const { nodes, materials } = useGLTF("/minispid.glb");

  return (
    <group
      {...props}
      dispose={null}
      position={props.position}
      rotation-y={props.rotationY}
      scale={props.scale}
    >
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry}>
        <meshBasicMaterial color="white" />
      </mesh>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Spider-Man_Redmesh"].geometry}
          material={materials.Red}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Spider-Man_Redmesh_1"].geometry}
          material={materials.Blue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Spider-Man_Redmesh_2"].geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Spider-Man_Redmesh_3"].geometry}
          material={materials.White}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/minispid.glb");
