/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/sketchfab_logo.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials["Sketchfab Blue"]}
      />
      <mesh geometry={nodes.Plane.geometry} material={materials.White} />
    </group>
  );
}

useGLTF.preload("/sketchfab_logo.glb");
