/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState } from "react";
import { useGLTF } from "@react-three/drei";
import SymbHeadDiv from "./3d-descriptions/SymbHead";
import { Select } from "@react-three/postprocessing";

export default function SymbHead(props) {
  const { nodes, materials } = useGLTF("/minifbsymbhead.glb");
  const [enabled, setEnabled] = useState(false);
  let timeoutId = null;

  const handlePointerOver = (event) => {
    event.stopPropagation();
    if (timeoutId) {
      clearTimeout(timeoutId);
    }
    document.body.style.cursor = "pointer";
    setEnabled(true);
  };

  const handlePointerOut = () => {
    if (timeoutId) {
      clearTimeout(timeoutId);
    }
    timeoutId = setTimeout(() => {
      document.body.style.cursor = "default";
      setEnabled(false);
    }, 10); // delay in milliseconds
  };

  return (
    <Select enabled={enabled && props.isActualWorkbenchClicked}>
      <group
        {...props}
        dispose={null}
        position={props.position.map(
          (value, index) => value + [0, -0.02, 0][index]
        )}
        rotation-y={props.rotationY + 0.4}
        scale={props.scale}
        onPointerOver={handlePointerOver}
        onPointerOut={handlePointerOut}
        onClick={(event) => {
          event.stopPropagation();
          props.setHtmlComponent(<SymbHeadDiv />);
          props.setShowDiv(true);
        }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.EYES_SYMB.geometry}
          material={materials.EYES}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.OUT_HEAD.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials["Material.002"]}
          position={[0, 0.017, 0]}
          scale={0.984}
        />
      </group>
    </Select>
  );
}

useGLTF.preload("/minifbsymbhead.glb");
