/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Webshooter(props) {
  const { nodes, materials } = useGLTF("/minifbwebshooter.glb");
  return (
    <group
      {...props}
      dispose={null}
      position={props.position}
      rotation-y={props.rotationY}
      scale={props.scale}
    >
      <group position={[0, 0.764, 0]} rotation={[-Math.PI / 4, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Base_Red.geometry}
          material={materials.Red}
          position={[0, -2.378, 0.238]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Black_Inside.geometry}
          material={materials.Black}
          position={[0, -3.256, 0.287]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bottom_Round_Base.geometry}
          material={materials.Black}
          position={[0, -3.256, 0.238]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Camera_Bottom_Surrounding001.geometry}
          material={materials.Gray}
          position={[0, -3.256, 0.238]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_Base.geometry}
          material={materials.Gray}
          position={[0, -0.262, 0.003]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.11, -0.228, -0.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_Base001.geometry}
          material={materials.Gray}
          position={[0, -0.262, 0.003]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.11, -0.228, -0.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Metal_Bottom_Back.geometry}
          material={materials.Gray}
          position={[-0.002, -3.251, 0.239]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Metal_Bottom_Top.geometry}
          material={materials.Gray}
          position={[0, -3.25, 0.238]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Metallic_Outer.geometry}
          material={materials.Gray}
          position={[0, -3.256, 0.238]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Camera_Bottom_Surrounding.geometry}
          material={materials.Gray}
          position={[0, -3.256, 0.238]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/minifbwebshooter.glb");
