/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/venom_platform.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials.Grass_1}
        position={[-22.739, 5.847, -17.278]}
        rotation={[Math.PI, -0.43, Math.PI]}
        scale={1.223}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials.Brown}
        position={[-22.739, 5.645, -17.278]}
        rotation={[Math.PI, -0.43, Math.PI]}
        scale={1.223}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials.Grass_1}
        position={[7.308, 2.47, -23.611]}
        rotation={[0, -0.481, 0]}
        scale={0.963}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials.Brown}
        position={[7.308, 2.311, -23.611]}
        rotation={[0, -0.481, 0]}
        scale={0.963}
      />
      <group
        position={[3.145, 3.215, -7.137]}
        rotation={[-1.466, 0.271, 3.065]}
        scale={[0.041, 0.102, 0.102]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_1.geometry}
          material={materials["Oscorp Purple"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_2.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_3.geometry}
          material={materials["Oscorp Gray"]}
        />
      </group>
      <group
        position={[-10.592, 3.215, -1.996]}
        rotation={[1.857, 0, -0.914]}
        scale={[0.237, 0.237, 0.063]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials["White Glow"]}
        />
      </group>
      <group
        position={[2.147, 3.215, -10.277]}
        rotation={[1.562, 0.286, 0.689]}
        scale={[0.237, 0.237, 0.063]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_1.geometry}
          material={materials["White Glow"]}
        />
      </group>
      <group
        position={[6.959, 1.226, 2.48]}
        rotation={[1.393, -0.787, 1.874]}
        scale={[1.507, 0.789, 0.12]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane172.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane172_1.geometry}
          material={materials["White Glow"]}
        />
      </group>
      <group
        position={[7.317, 0.786, -2.392]}
        rotation={[1.141, -0.685, 1.054]}
        scale={[1.507, 0.789, 0.12]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane173.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane173_1.geometry}
          material={materials["White Glow"]}
        />
      </group>
      <group
        position={[5.856, 0.216, 3.053]}
        rotation={[2.807, -1.012, 2.774]}
        scale={[2.864, 1.699, 1.069]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane174.geometry}
          material={materials["Brick 1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane174_1.geometry}
          material={materials["Brick 2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane174_2.geometry}
          material={materials["Brick 3"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane174_3.geometry}
          material={materials["Brick 4"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane174_4.geometry}
          material={materials["Brick 5"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane174_5.geometry}
          material={materials["Dirty Gray"]}
        />
      </group>
      <group
        position={[7.472, 0.462, 0.765]}
        rotation={[0.927, -1.242, 0.93]}
        scale={[2.864, 1.699, 1.069]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane175.geometry}
          material={materials["Brick 1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane175_1.geometry}
          material={materials["Brick 2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane175_2.geometry}
          material={materials["Brick 3"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane175_3.geometry}
          material={materials["Brick 4"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane175_4.geometry}
          material={materials["Brick 5"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane175_5.geometry}
          material={materials["Dirty Gray"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dirty_Plane.geometry}
        material={materials["Dirty Gray"]}
        position={[5.855, 0.05, 1.187]}
        rotation={[0.009, -0.015, -0.001]}
        scale={1.356}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dirty_Plane001.geometry}
        material={materials["Dirty Beige"]}
        position={[4.255, 0.114, 6.604]}
        rotation={[0.041, -1.357, 0.039]}
        scale={1.356}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dirty_Plane002.geometry}
        material={materials["Dirty Gray 2"]}
        position={[-6.222, 0.05, -0.52]}
        rotation={[-3.127, -0.28, 3.137]}
        scale={1.356}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dirty_Plane003.geometry}
        material={materials["Dirty Beige"]}
        position={[-5.677, 0.057, -2.269]}
        rotation={[0.03, -0.548, 0.003]}
        scale={1.356}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder030.geometry}
        material={materials.Black}
        position={[-12.021, 10.022, -5.791]}
        rotation={[2.92, -0.376, -0.176]}
        scale={[0.453, 0.696, 0.519]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder047.geometry}
        material={materials.Black}
        position={[3.83, 2.235, 9.039]}
        rotation={[3.116, -1.296, 3.115]}
        scale={-0.281}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder058.geometry}
        material={materials.Black}
        position={[-7.641, 3.113, 5.277]}
        rotation={[0.364, 0.499, -0.279]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials.Black}
        position={[-5.249, -0.039, -10.78]}
        rotation={[-2.053, 0.769, 1.071]}
        scale={-0.272}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials.Black}
        position={[11.219, 2.235, -7.656]}
        rotation={[3.116, -1.296, 3.115]}
        scale={-0.281}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials.Black}
        position={[0.516, 4.768, -6.528]}
        rotation={[-2.824, 0.8, -0.303]}
        scale={[0.196, 0.302, 0.225]}
      />
      <group
        position={[-7.399, 9.262, -22.189]}
        rotation={[-0.118, 0.111, 0.254]}
        scale={2.379}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011_1.geometry}
          material={materials.Green}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011_2.geometry}
          material={materials.White}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials["Oscorp Gray"]}
        position={[-4.525, 2.056, -14.41]}
        rotation={[-0.118, 0.111, 0.254]}
        scale={2.379}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials.White}
        position={[-1.322, 1.657, 7.782]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.107}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials.Yellow}
        position={[-1.952, 1.872, 7.43]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials.Yellow}
        position={[-2.867, -0.655, 7.108]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials.Yellow}
        position={[-2.867, -0.655, 7.108]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={materials.Yellow}
        position={[-2.47, -0.718, 7.283]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane016.geometry}
        material={materials.Yellow}
        position={[-2.523, -1.111, 7.272]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane017.geometry}
        material={materials.Yellow}
        position={[-1.84, 2.675, 7.455]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane018.geometry}
        material={materials.Yellow}
        position={[-1.903, 2.269, 7.44]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane019.geometry}
        material={materials.Yellow}
        position={[-2.526, 1.956, 7.177]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane020.geometry}
        material={materials.Yellow}
        position={[-3.442, -0.571, 6.854]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane021.geometry}
        material={materials.Yellow}
        position={[-3.442, -0.571, 6.854]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane022.geometry}
        material={materials.Yellow}
        position={[-3.044, -0.634, 7.03]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane023.geometry}
        material={materials.Yellow}
        position={[-3.098, -1.027, 7.018]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane024.geometry}
        material={materials.Yellow}
        position={[-2.414, 2.759, 7.201]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane025.geometry}
        material={materials.Yellow}
        position={[-2.477, 2.353, 7.186]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane026.geometry}
        material={materials.Yellow}
        position={[-3.256, 2.07, 6.855]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027.geometry}
        material={materials.Yellow}
        position={[-4.172, -0.457, 6.532]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane028.geometry}
        material={materials.Yellow}
        position={[-4.172, -0.457, 6.532]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane029.geometry}
        material={materials.Yellow}
        position={[-3.774, -0.519, 6.707]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane030.geometry}
        material={materials.Yellow}
        position={[-3.828, -0.913, 6.696]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane031.geometry}
        material={materials.Yellow}
        position={[-3.144, 2.873, 6.879]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane032.geometry}
        material={materials.Yellow}
        position={[-3.207, 2.467, 6.864]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane033.geometry}
        material={materials.Yellow}
        position={[-3.83, 2.16, 6.602]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane034.geometry}
        material={materials.Yellow}
        position={[-4.745, -0.367, 6.279]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane035.geometry}
        material={materials.Yellow}
        position={[-4.745, -0.367, 6.279]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane036.geometry}
        material={materials.Yellow}
        position={[-4.348, -0.429, 6.454]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane037.geometry}
        material={materials.Yellow}
        position={[-4.401, -0.823, 6.443]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane038.geometry}
        material={materials.Yellow}
        position={[-3.718, 2.963, 6.626]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane039.geometry}
        material={materials.Yellow}
        position={[-3.781, 2.557, 6.611]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane040.geometry}
        material={materials.Yellow}
        position={[-5.196, 2.299, 6.001]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane041.geometry}
        material={materials.Yellow}
        position={[-6.112, -0.229, 5.678]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane042.geometry}
        material={materials.Yellow}
        position={[-6.112, -0.229, 5.678]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane043.geometry}
        material={materials.Yellow}
        position={[-5.714, -0.291, 5.854]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane044.geometry}
        material={materials.Yellow}
        position={[-5.768, -0.684, 5.842]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane045.geometry}
        material={materials.Yellow}
        position={[-5.084, 3.101, 6.025]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane046.geometry}
        material={materials.Yellow}
        position={[-5.147, 2.695, 6.01]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane047.geometry}
        material={materials.Yellow}
        position={[-5.76, 2.381, 5.752]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane048.geometry}
        material={materials.Yellow}
        position={[-6.676, -0.146, 5.429]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane049.geometry}
        material={materials.Yellow}
        position={[-6.676, -0.146, 5.429]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane050.geometry}
        material={materials.Yellow}
        position={[-6.279, -0.209, 5.605]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane051.geometry}
        material={materials.Yellow}
        position={[-6.332, -0.602, 5.593]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane052.geometry}
        material={materials.Yellow}
        position={[-5.648, 3.184, 5.777]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane053.geometry}
        material={materials.Yellow}
        position={[-5.711, 2.778, 5.761]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane054.geometry}
        material={materials.Yellow}
        position={[-5.507, 0.692, 5.914]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane055.geometry}
        material={materials.Yellow}
        position={[-6.369, -1.688, 5.61]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.942}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane056.geometry}
        material={materials.Yellow}
        position={[-6.369, -1.688, 5.61]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.942}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane057.geometry}
        material={materials.Yellow}
        position={[-5.995, -1.746, 5.775]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.942}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane058.geometry}
        material={materials.Yellow}
        position={[-6.046, -2.117, 5.765]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.942}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane059.geometry}
        material={materials.Yellow}
        position={[-5.402, 1.448, 5.937]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane060.geometry}
        material={materials.Yellow}
        position={[-5.461, 1.066, 5.923]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane061.geometry}
        material={materials.Yellow}
        position={[-6.038, 0.77, 5.68]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane062.geometry}
        material={materials.Yellow}
        position={[-6.9, -1.61, 5.376]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.942}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane063.geometry}
        material={materials.Yellow}
        position={[-6.9, -1.61, 5.376]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.942}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane064.geometry}
        material={materials.Yellow}
        position={[-6.526, -1.669, 5.541]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.942}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane065.geometry}
        material={materials.Yellow}
        position={[-6.577, -2.039, 5.53]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.942}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane066.geometry}
        material={materials.Yellow}
        position={[-5.933, 1.525, 5.703]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane067.geometry}
        material={materials.Yellow}
        position={[-5.992, 1.143, 5.689]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane068.geometry}
        material={materials.Yellow}
        position={[-0.504, -0.081, 8.122]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane069.geometry}
        material={materials.Yellow}
        position={[-1.366, -2.461, 7.818]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.942}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane070.geometry}
        material={materials.Yellow}
        position={[-1.366, -2.461, 7.818]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.942}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane071.geometry}
        material={materials.Yellow}
        position={[-0.992, -2.52, 7.983]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.942}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane072.geometry}
        material={materials.Yellow}
        position={[-1.043, -2.89, 7.972]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.942}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane073.geometry}
        material={materials.Yellow}
        position={[-0.399, 0.675, 8.145]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane074.geometry}
        material={materials.Yellow}
        position={[-0.458, 0.292, 8.13]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane075.geometry}
        material={materials.Yellow}
        position={[0.019, 1.462, 8.303]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane076.geometry}
        material={materials.Yellow}
        position={[-0.897, -1.066, 7.98]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane077.geometry}
        material={materials.Yellow}
        position={[-0.897, -1.066, 7.98]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane078.geometry}
        material={materials.Yellow}
        position={[-0.499, -1.128, 8.156]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane079.geometry}
        material={materials.Yellow}
        position={[-0.553, -1.521, 8.144]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane080.geometry}
        material={materials.Yellow}
        position={[0.131, 2.265, 8.327]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane081.geometry}
        material={materials.Yellow}
        position={[0.068, 1.859, 8.312]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane082.geometry}
        material={materials.Yellow}
        position={[-0.545, 1.544, 8.054]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane083.geometry}
        material={materials.Yellow}
        position={[-1.461, -0.983, 7.732]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane084.geometry}
        material={materials.Yellow}
        position={[-1.461, -0.983, 7.732]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane085.geometry}
        material={materials.Yellow}
        position={[-1.064, -1.045, 7.907]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane086.geometry}
        material={materials.Yellow}
        position={[-1.117, -1.439, 7.895]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane087.geometry}
        material={materials.Yellow}
        position={[-0.433, 2.347, 8.079]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane088.geometry}
        material={materials.Yellow}
        position={[-0.496, 1.941, 8.064]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane089.geometry}
        material={materials.Yellow}
        position={[-1.827, 0.046, 7.54]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.028}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane090.geometry}
        material={materials.Yellow}
        position={[-2.298, -1.256, 7.374]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.515}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane091.geometry}
        material={materials.Yellow}
        position={[-2.298, -1.256, 7.374]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.515}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane092.geometry}
        material={materials.Yellow}
        position={[-2.094, -1.288, 7.465]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.515}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane093.geometry}
        material={materials.Yellow}
        position={[-2.121, -1.49, 7.459]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.515}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane094.geometry}
        material={materials.Yellow}
        position={[-1.769, 0.459, 7.553]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.028}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane095.geometry}
        material={materials.Yellow}
        position={[-1.802, 0.25, 7.545]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.028}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane096.geometry}
        material={materials.Yellow}
        position={[-4.461, 0.453, 6.378]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.028}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane097.geometry}
        material={materials.Yellow}
        position={[-4.933, -0.848, 6.212]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.515}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane098.geometry}
        material={materials.Yellow}
        position={[-4.933, -0.848, 6.212]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.515}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane099.geometry}
        material={materials.Yellow}
        position={[-4.728, -0.88, 6.302]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.515}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane100.geometry}
        material={materials.Yellow}
        position={[-4.756, -1.083, 6.296]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.515}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane101.geometry}
        material={materials.Yellow}
        position={[-4.404, 0.867, 6.391]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.028}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane102.geometry}
        material={materials.Yellow}
        position={[-4.436, 0.658, 6.383]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.028}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane103.geometry}
        material={materials.Yellow}
        position={[-3.117, 0.304, 6.969]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane104.geometry}
        material={materials.Yellow}
        position={[-3.978, -2.074, 6.666]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.941}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane105.geometry}
        material={materials.Yellow}
        position={[-3.978, -2.074, 6.666]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.941}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane106.geometry}
        material={materials.Yellow}
        position={[-3.604, -2.132, 6.831]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.941}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane107.geometry}
        material={materials.Yellow}
        position={[-3.655, -2.502, 6.82]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.941}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane108.geometry}
        material={materials.Yellow}
        position={[-3.012, 1.059, 6.992]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane109.geometry}
        material={materials.Yellow}
        position={[-3.071, 0.677, 6.978]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.052}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane110.geometry}
        material={materials.White}
        position={[0.292, 2.774, 8.395]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.017}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane111.geometry}
        material={materials.White}
        position={[0.035, 2.812, 8.281]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.929}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane112.geometry}
        material={materials.White}
        position={[-0.255, 2.84, 8.154]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane113.geometry}
        material={materials.White}
        position={[-0.609, 2.909, 7.997]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane114.geometry}
        material={materials.White}
        position={[-4.451, 3.504, 6.302]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane115.geometry}
        material={materials.White}
        position={[-4.767, 3.572, 6.162]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane116.geometry}
        material={materials.White}
        position={[-4.945, 3.602, 6.083]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane117.geometry}
        material={materials.White}
        position={[-5.138, 3.63, 5.998]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane118.geometry}
        material={materials.White}
        position={[-5.347, 3.663, 5.906]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane119.geometry}
        material={materials.White}
        position={[-5.496, 3.682, 5.84]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.929}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane120.geometry}
        material={materials.White}
        position={[-5.781, 3.732, 5.715]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane121.geometry}
        material={materials.White}
        position={[-6.106, 3.783, 5.571]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.055}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane122.geometry}
        material={materials.White}
        position={[-5.463, 1.797, 5.912]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.024}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane123.geometry}
        material={materials.White}
        position={[-4.319, 1.076, 6.433]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.024}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane124.geometry}
        material={materials.White}
        position={[-3.133, 1.429, 6.941]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.026}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane125.geometry}
        material={materials.White}
        position={[-1.688, 0.669, 7.594]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.024}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane126.geometry}
        material={materials.White}
        position={[-5.53, 1.808, 5.883]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.436}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane127.geometry}
        material={materials.White}
        position={[-5.812, 1.853, 5.758]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.436}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane128.geometry}
        material={materials.White}
        position={[-4.379, 1.086, 6.407]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.436}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane129.geometry}
        material={materials.White}
        position={[-1.75, 0.677, 7.567]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.436}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane130.geometry}
        material={materials.White}
        position={[-0.245, 0.983, 8.215]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.436}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane131.geometry}
        material={materials.White}
        position={[-0.141, 0.966, 8.261]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.436}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane132.geometry}
        material={materials.White}
        position={[-0.376, 1.006, 8.157]}
        rotation={[-1.538, 0.144, -0.416]}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane133.geometry}
        material={materials.White}
        position={[-0.539, 1.019, 8.085]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane134.geometry}
        material={materials.White}
        position={[-0.686, 1.05, 8.02]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane135.geometry}
        material={materials.White}
        position={[-1.881, 0.697, 7.509]}
        rotation={[-1.539, 0.142, 2.726]}
        scale={0.024}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane136.geometry}
        material={materials.White}
        position={[-5.708, 1.836, 5.804]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.436}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane137.geometry}
        material={materials.White}
        position={[-4.51, 1.105, 6.349]}
        rotation={[-1.539, 0.142, 2.726]}
        scale={0.024}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane138.geometry}
        material={materials.White}
        position={[-3.223, 1.443, 6.901]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.026}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane139.geometry}
        material={materials.White}
        position={[-2.982, 1.404, 7.007]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.026}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane140.geometry}
        material={materials.White}
        position={[-2.837, 1.391, 7.071]}
        rotation={[-0.03, -0.411, 2.987]}
        scale={0.47}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane141.geometry}
        material={materials.White}
        position={[-2.605, 1.346, 7.173]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.436}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane142.geometry}
        material={materials.White}
        position={[-2.716, 1.362, 7.124]}
        rotation={[3.111, 0.411, -2.987]}
        scale={0.436}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane143.geometry}
        material={materials.White}
        position={[-3.338, 1.461, 6.85]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.026}
      />
      <group
        position={[-2.844, 2.419, 7.098]}
        rotation={[1.603, -0.142, -2.726]}
        scale={[1.448, 0.7, 0.7]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane149_1.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane149_2.geometry}
          material={materials.White}
        />
      </group>
      <group
        position={[-0.284, 1.915, 8.231]}
        rotation={[1.603, -0.142, -2.726]}
        scale={[0.802, 0.616, 0.616]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane153_1.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane153_2.geometry}
          material={materials.White}
        />
      </group>
      <group
        position={[-5.459, 2.725, 5.947]}
        rotation={[1.603, -0.142, -2.726]}
        scale={[0.802, 0.616, 0.616]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane154_1.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane154_2.geometry}
          material={materials.White}
        />
      </group>
      <group
        position={[-0.513, 0.311, 8.18]}
        rotation={[1.603, -0.142, -2.726]}
        scale={[0.689, 0.529, 0.529]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane155_1.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane155_2.geometry}
          material={materials.White}
        />
      </group>
      <group
        position={[-5.734, 1.128, 5.876]}
        rotation={[1.603, -0.142, -2.726]}
        scale={[0.689, 0.529, 0.529]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane156_1.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane156_2.geometry}
          material={materials.White}
        />
      </group>
      <group
        position={[-3.117, 0.701, 7.031]}
        rotation={[1.603, -0.142, -2.726]}
        scale={[0.701, 0.539, 0.539]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane157_1.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane157_2.geometry}
          material={materials.White}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane150.geometry}
        material={materials.Black}
        position={[-4.47, 0.667, 6.441]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.288}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane151.geometry}
        material={materials.Black}
        position={[-1.835, 0.254, 7.604]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.288}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane152.geometry}
        material={materials.Black}
        position={[-1.325, 1.655, 7.784]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.129}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane153.geometry}
        material={materials.Black}
        position={[-4.52, 2.155, 6.374]}
        rotation={[1.603, -0.142, -2.726]}
        scale={0.129}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane154.geometry}
        material={materials["Oscorp Gray"]}
        position={[-2.891, 2.096, 7.105]}
        rotation={[1.603, -0.142, -2.726]}
        scale={[3.935, 1, 2.188]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane155.geometry}
        material={materials.Yellow}
        position={[-3.574, -0.325, 6.789]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane156.geometry}
        material={materials.Yellow}
        position={[-3.603, -0.528, 6.783]}
        rotation={[3.111, 0.411, -2.987]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials.Brown}
        position={[0, -0.108, 0]}
      />
      <group position={[-1.739, 0.06, -5.685]} scale={3.08}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_1.geometry}
          material={materials["Dirty Beige 1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_2.geometry}
          material={materials.Yellow}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials["Dirty Beige 1"]}
        position={[-1.739, 0.145, -6.351]}
        rotation={[0.24, 0.414, -0.04]}
        scale={3.08}
      />
      <group position={[-1.726, 0.137, -5.547]} scale={2.58}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane165.geometry}
          material={materials["Dirty Beige 1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane165_1.geometry}
          material={materials.Yellow}
        />
      </group>
      <group
        position={[5.508, 0.046, -4.378]}
        rotation={[0, -0.588, 0]}
        scale={2.58}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane166.geometry}
          material={materials["Dirty Beige 1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane166_1.geometry}
          material={materials.Yellow}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials.Black}
        position={[-8.206, 0.149, 2.678]}
        rotation={[0.399, 1.263, -2.188]}
        scale={0.201}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials.Black}
        position={[3.424, 0.961, -7.817]}
        rotation={[-1.546, 0.736, 0.704]}
        scale={-0.368}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials.Black}
        position={[6.967, 0.758, 7.484]}
        rotation={[0.643, 0.533, 1.427]}
        scale={0.307}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_1.geometry}
        material={materials.Grass_1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_2.geometry}
        material={materials.White}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_3.geometry}
        material={materials["Dark Blue"]}
      />
    </group>
  );
}

useGLTF.preload("/venom_platform.glb");
