/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/venom_platform3.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-15.798, 8.195, -22.017]}
        rotation={[0.266, -0.207, -0.287]}
      >
        <mesh
          geometry={nodes.Cube005.geometry}
          material={materials["Beige Concrete Shadow"]}
          position={[0.401, -0.041, 0.116]}
          scale={[0.135, 0.055, 0.135]}
        />
        <mesh
          geometry={nodes.Cube006.geometry}
          material={materials["Beige Concrete Shadow"]}
          position={[0.5, -0.041, 0.116]}
          scale={[0.135, 0.055, 0.135]}
        />
        <mesh
          geometry={nodes.Cube007.geometry}
          material={materials["Beige Concrete Shadow"]}
          position={[0.263, 0.11, 2.116]}
          rotation={[-Math.PI, 0.365, -Math.PI]}
          scale={[0.135, 0.055, 0.135]}
        />
        <mesh
          geometry={nodes.CurlyCurve003.geometry}
          material={materials.Black}
          position={[-0.445, -0.082, -1.505]}
          rotation={[0, 1.544, 0]}
          scale={1.606}
        />
        <mesh
          geometry={nodes.Dirty_Plane004.geometry}
          material={materials["Dirty Gray"]}
          position={[1.207, -0.045, 0.033]}
          rotation={[0.011, -0.666, 0.006]}
          scale={[0.601, 0.013, 0.601]}
        />
        <group
          position={[-0.754, 0.276, 1.262]}
          rotation={[Math.PI / 2, 0, 0.811]}
          scale={[1.468, 0.87, 0.548]}
        >
          <mesh
            geometry={nodes.Plane193.geometry}
            material={materials["Brick 1"]}
          />
          <mesh
            geometry={nodes.Plane193_1.geometry}
            material={materials["Brick 2"]}
          />
          <mesh
            geometry={nodes.Plane193_2.geometry}
            material={materials["Brick 3"]}
          />
          <mesh
            geometry={nodes.Plane193_3.geometry}
            material={materials["Brick 4"]}
          />
          <mesh
            geometry={nodes.Plane193_4.geometry}
            material={materials["Brick 5"]}
          />
          <mesh
            geometry={nodes.Plane193_5.geometry}
            material={materials["Brick Tops"]}
          />
        </group>
        <group
          position={[-3.233, 0.501, -0.317]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1.834, 1.088, 0.684]}
        >
          <mesh
            geometry={nodes.Plane194.geometry}
            material={materials["Brick 1"]}
          />
          <mesh
            geometry={nodes.Plane194_1.geometry}
            material={materials["Brick 2"]}
          />
          <mesh
            geometry={nodes.Plane194_2.geometry}
            material={materials["Brick 3"]}
          />
          <mesh
            geometry={nodes.Plane194_3.geometry}
            material={materials["Brick 4"]}
          />
          <mesh
            geometry={nodes.Plane194_4.geometry}
            material={materials["Brick 5"]}
          />
          <mesh
            geometry={nodes.Plane194_5.geometry}
            material={materials["Brick Tops"]}
          />
        </group>
        <group
          position={[2.51, 0.603, -2.238]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1.834, 1.088, 0.684]}
        >
          <mesh
            geometry={nodes.Plane174_1.geometry}
            material={materials["Brick 1"]}
          />
          <mesh
            geometry={nodes.Plane174_2.geometry}
            material={materials["Brick 2"]}
          />
          <mesh
            geometry={nodes.Plane174_3.geometry}
            material={materials["Brick 3"]}
          />
          <mesh
            geometry={nodes.Plane174_4.geometry}
            material={materials["Brick 4"]}
          />
          <mesh
            geometry={nodes.Plane174_5.geometry}
            material={materials["Brick 5"]}
          />
          <mesh
            geometry={nodes.Plane174_6.geometry}
            material={materials["Brick Tops"]}
          />
        </group>
        <group
          position={[-0.667, 0.376, -2.124]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1.468, 0.87, 0.548]}
        >
          <mesh
            geometry={nodes.Plane175_1.geometry}
            material={materials["Brick 1"]}
          />
          <mesh
            geometry={nodes.Plane175_2.geometry}
            material={materials["Brick 2"]}
          />
          <mesh
            geometry={nodes.Plane175_3.geometry}
            material={materials["Brick 3"]}
          />
          <mesh
            geometry={nodes.Plane175_4.geometry}
            material={materials["Brick 4"]}
          />
          <mesh
            geometry={nodes.Plane175_5.geometry}
            material={materials["Brick 5"]}
          />
          <mesh
            geometry={nodes.Plane175_6.geometry}
            material={materials["Brick Tops"]}
          />
        </group>
        <group
          position={[-4.898, 0, 3.05]}
          rotation={[0, -1.45, 0]}
          scale={1.689}
        >
          <mesh
            geometry={nodes.Plane170_1.geometry}
            material={materials["Beige Concrete Base"]}
          />
          <mesh
            geometry={nodes.Plane170_2.geometry}
            material={materials["Beige Concrete Shadow"]}
          />
        </group>
        <mesh
          geometry={nodes.Plane174.geometry}
          material={materials["Brown Steel Grid"]}
          position={[1.128, -0.034, 0.319]}
          rotation={[0, 0.003, 0]}
          scale={[0.02, 0.114, 0.114]}
        />
        <mesh
          geometry={nodes.Plane175.geometry}
          material={materials["Brown Steel Grid"]}
          position={[-0.265, -0.034, 1.441]}
          rotation={[-Math.PI, 0.037, -Math.PI]}
          scale={[0.02, 0.114, 0.114]}
        />
        <mesh
          geometry={nodes.Plane176.geometry}
          material={materials["Brown Steel Grid"]}
          position={[-1.727, -0.034, 2.072]}
          rotation={[Math.PI, -0.14, Math.PI]}
          scale={[0.02, 0.114, 0.114]}
        />
        <mesh
          geometry={nodes.Plane177.geometry}
          material={materials["Brown Steel Grid"]}
          position={[-0.645, -0.359, 3.815]}
          rotation={[Math.PI, -0.099, Math.PI]}
          scale={[0.02, 0.114, 0.114]}
        />
        <mesh
          geometry={nodes.Plane178.geometry}
          material={materials["Brown Steel Grid"]}
          position={[3.832, -0.563, 4.015]}
          rotation={[Math.PI, -0.099, Math.PI]}
          scale={[0.02, 0.114, 0.114]}
        />
        <mesh
          geometry={nodes.Plane179.geometry}
          material={materials["Brown Steel Grid"]}
          position={[5.678, -0.034, -2.734]}
          rotation={[0, -1.383, 0]}
          scale={[0.02, 0.114, 0.114]}
        />
      </group>
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials["Beige Concrete Shadow"]}
        position={[-1.141, 1.567, 38.81]}
        rotation={[0.9, 0.873, -1.047]}
        scale={[0.302, 0.123, 0.302]}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={materials["Beige Concrete Shadow"]}
        position={[46.725, 2.957, 11.91]}
        rotation={[2.58, 0.329, 3.063]}
        scale={[0.302, 0.123, 0.302]}
      />
      <group
        position={[12.278, 11.853, -22.929]}
        rotation={[0.324, 0.389, 0.537]}
      >
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials["Beige Concrete Shadow"]}
          position={[-2.799, -0.041, 0.087]}
          scale={[0.135, 0.055, 0.135]}
        />
        <mesh
          geometry={nodes.Cube008.geometry}
          material={materials["Beige Concrete Shadow"]}
          position={[-1.839, -0.133, 3.122]}
          rotation={[0, 0.778, 0]}
          scale={[0.207, 0.084, 0.207]}
        />
        <group position={[5.117, 0, -1.416]} scale={3.737}>
          <mesh
            geometry={nodes.Plane198.geometry}
            material={materials["Beige Concrete Shadow"]}
          />
          <mesh
            geometry={nodes.Plane198_1.geometry}
            material={materials["Beige Concrete Base"]}
          />
        </group>
        <group
          position={[-4.472, 0, -4.98]}
          rotation={[0, -0.489, 0]}
          scale={3.737}
        >
          <mesh
            geometry={nodes.Plane199.geometry}
            material={materials["Beige Concrete Shadow"]}
          />
          <mesh
            geometry={nodes.Plane199_1.geometry}
            material={materials["Beige Concrete Base"]}
          />
        </group>
        <group
          position={[0.958, -0.273, 4.022]}
          rotation={[0.214, -0.25, 0.108]}
          scale={2.507}
        >
          <mesh
            geometry={nodes.Plane200.geometry}
            material={materials["Beige Concrete Shadow"]}
          />
          <mesh
            geometry={nodes.Plane200_1.geometry}
            material={materials["Beige Concrete Base"]}
          />
        </group>
        <group
          position={[-6.876, -1.024, 3.258]}
          rotation={[0.234, 0.091, 0.207]}
          scale={2.693}
        >
          <mesh
            geometry={nodes.Plane201.geometry}
            material={materials["Beige Concrete Shadow"]}
          />
          <mesh
            geometry={nodes.Plane201_1.geometry}
            material={materials["Beige Concrete Base"]}
          />
        </group>
        <group
          position={[-4.283, 0.141, -6.045]}
          rotation={[0.076, -0.117, -0.007]}
        >
          <mesh
            geometry={nodes.Plane210.geometry}
            material={materials["Beige Concrete Base"]}
          />
          <mesh
            geometry={nodes.Plane210_1.geometry}
            material={materials["Beige Concrete Shadow"]}
          />
        </group>
        <group
          position={[-6.191, 0.527, -4.984]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1.834, 1.088, 0.684]}
        >
          <mesh
            geometry={nodes.Plane211.geometry}
            material={materials["Brick 1"]}
          />
          <mesh
            geometry={nodes.Plane211_1.geometry}
            material={materials["Brick 2"]}
          />
          <mesh
            geometry={nodes.Plane211_2.geometry}
            material={materials["Brick 3"]}
          />
          <mesh
            geometry={nodes.Plane211_3.geometry}
            material={materials["Brick 4"]}
          />
          <mesh
            geometry={nodes.Plane211_4.geometry}
            material={materials["Brick 5"]}
          />
          <mesh
            geometry={nodes.Plane211_5.geometry}
            material={materials["Brick Tops"]}
          />
        </group>
        <group
          position={[6.351, 0.629, -1.239]}
          rotation={[Math.PI / 2, 0, -0.169]}
          scale={[1.834, 1.088, 0.684]}
        >
          <mesh
            geometry={nodes.Plane212.geometry}
            material={materials["Brick 1"]}
          />
          <mesh
            geometry={nodes.Plane212_1.geometry}
            material={materials["Brick 2"]}
          />
          <mesh
            geometry={nodes.Plane212_2.geometry}
            material={materials["Brick 3"]}
          />
          <mesh
            geometry={nodes.Plane212_3.geometry}
            material={materials["Brick 4"]}
          />
          <mesh
            geometry={nodes.Plane212_4.geometry}
            material={materials["Brick 5"]}
          />
          <mesh
            geometry={nodes.Plane212_5.geometry}
            material={materials["Brick Tops"]}
          />
        </group>
        <group
          position={[-1.447, 0.402, -4.289]}
          rotation={[Math.PI / 2, 0, -0.125]}
          scale={[1.468, 0.87, 0.548]}
        >
          <mesh
            geometry={nodes.Plane213.geometry}
            material={materials["Brick 1"]}
          />
          <mesh
            geometry={nodes.Plane213_1.geometry}
            material={materials["Brick 2"]}
          />
          <mesh
            geometry={nodes.Plane213_2.geometry}
            material={materials["Brick 3"]}
          />
          <mesh
            geometry={nodes.Plane213_3.geometry}
            material={materials["Brick 4"]}
          />
          <mesh
            geometry={nodes.Plane213_4.geometry}
            material={materials["Brick 5"]}
          />
          <mesh
            geometry={nodes.Plane213_5.geometry}
            material={materials["Brick Tops"]}
          />
        </group>
        <group
          position={[-0.437, 0.026, 2.518]}
          rotation={[1.758, 0.105, -0.08]}
          scale={[1.834, 1.088, 0.684]}
        >
          <mesh
            geometry={nodes.Plane214.geometry}
            material={materials["Brick 1"]}
          />
          <mesh
            geometry={nodes.Plane214_1.geometry}
            material={materials["Brick 2"]}
          />
          <mesh
            geometry={nodes.Plane214_2.geometry}
            material={materials["Brick 3"]}
          />
          <mesh
            geometry={nodes.Plane214_3.geometry}
            material={materials["Brick 4"]}
          />
          <mesh
            geometry={nodes.Plane214_4.geometry}
            material={materials["Brick 5"]}
          />
          <mesh
            geometry={nodes.Plane214_5.geometry}
            material={materials["Brick Tops"]}
          />
        </group>
        <group
          position={[3.366, -0.283, 4.248]}
          rotation={[1.758, 0.105, -0.205]}
          scale={[1.468, 0.87, 0.548]}
        >
          <mesh
            geometry={nodes.Plane215.geometry}
            material={materials["Brick 1"]}
          />
          <mesh
            geometry={nodes.Plane215_1.geometry}
            material={materials["Brick 3"]}
          />
          <mesh
            geometry={nodes.Plane215_2.geometry}
            material={materials["Brick 4"]}
          />
          <mesh
            geometry={nodes.Plane215_3.geometry}
            material={materials["Brick 5"]}
          />
          <mesh
            geometry={nodes.Plane215_4.geometry}
            material={materials["Brick Tops"]}
          />
        </group>
        <group
          position={[-4.906, -0.728, 2.866]}
          rotation={[1.824, 0.207, -0.306]}
          scale={[1.468, 0.87, 0.548]}
        >
          <mesh
            geometry={nodes.Plane216.geometry}
            material={materials["Brick 1"]}
          />
          <mesh
            geometry={nodes.Plane216_1.geometry}
            material={materials["Brick 3"]}
          />
          <mesh
            geometry={nodes.Plane216_2.geometry}
            material={materials["Brick 4"]}
          />
          <mesh
            geometry={nodes.Plane216_3.geometry}
            material={materials["Brick 5"]}
          />
          <mesh
            geometry={nodes.Plane216_4.geometry}
            material={materials["Brick Tops"]}
          />
        </group>
        <mesh
          geometry={nodes.Plane166.geometry}
          material={materials["Brown Steel Grid"]}
          position={[-3.121, -0.127, 2.182]}
          rotation={[0, 0.648, 0]}
          scale={[0.02, 0.114, 0.114]}
        />
        <mesh
          geometry={nodes.Plane167.geometry}
          material={materials["Brown Steel Grid"]}
          position={[-0.832, -0.127, 1.301]}
          rotation={[0, -0.624, 0]}
          scale={[0.02, 0.114, 0.114]}
        />
        <mesh
          geometry={nodes.Plane168.geometry}
          material={materials["Brown Steel Grid"]}
          position={[4.761, -0.083, 0.545]}
          rotation={[0, 0.092, 0]}
          scale={[0.02, 0.114, 0.114]}
        />
        <mesh
          geometry={nodes.Plane169.geometry}
          material={materials["Brown Steel Grid"]}
          position={[1.72, -0.083, -1.078]}
          rotation={[0, 0.478, 0]}
          scale={[0.02, 0.114, 0.114]}
        />
        <mesh
          geometry={nodes.Plane170.geometry}
          material={materials["Brown Steel Grid"]}
          position={[6.524, -0.083, -2.026]}
          rotation={[0, 1.309, 0]}
          scale={[0.02, 0.114, 0.114]}
        />
        <mesh
          geometry={nodes.Plane171.geometry}
          material={materials["Brown Steel Grid"]}
          position={[-7.056, -0.045, -3.028]}
          rotation={[0, -0.303, 0]}
          scale={[0.02, 0.114, 0.114]}
        />
        <mesh
          geometry={nodes.Plane172.geometry}
          material={materials["Brown Steel Grid"]}
          position={[-4.779, -0.117, -0.318]}
          rotation={[-Math.PI, 0.469, -Math.PI]}
          scale={[0.02, 0.114, 0.114]}
        />
        <mesh
          geometry={nodes.Plane173.geometry}
          material={materials["Brown Steel Grid"]}
          position={[-7.593, -0.117, -1.911]}
          rotation={[-Math.PI, 0.599, -Math.PI]}
          scale={[0.02, 0.114, 0.114]}
        />
      </group>
      <group
        position={[38.309, 12.801, 14.847]}
        rotation={[2.966, 0.409, 2.057]}
        scale={[1.834, 1.088, 0.684]}
      >
        <mesh
          geometry={nodes.Plane259.geometry}
          material={materials["Brick 1"]}
        />
        <mesh
          geometry={nodes.Plane259_1.geometry}
          material={materials["Brick 2"]}
        />
        <mesh
          geometry={nodes.Plane259_2.geometry}
          material={materials["Brick 3"]}
        />
        <mesh
          geometry={nodes.Plane259_3.geometry}
          material={materials["Brick 4"]}
        />
        <mesh
          geometry={nodes.Plane259_4.geometry}
          material={materials["Brick 5"]}
        />
        <mesh
          geometry={nodes.Plane259_5.geometry}
          material={materials["Brick Tops"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials["Beige Concrete Shadow"]}
        position={[0, -0.04, 0]}
        scale={[0.135, 0.055, 0.135]}
      />
      <mesh
        geometry={nodes.CurlyCurve001.geometry}
        material={materials.Black}
        position={[3.757, -0.067, -1.035]}
        scale={1.755}
      />
      <mesh
        geometry={nodes.CurlyCurve002.geometry}
        material={materials.Black}
        position={[-3.491, -0.08, 0.803]}
        rotation={[-Math.PI, 0.258, -Math.PI]}
        scale={1.755}
      />
      <group position={[0.018, -0.003, 0.014]}>
        <mesh
          geometry={nodes.Plane_1.geometry}
          material={materials["Beige Concrete Base"]}
        />
        <mesh
          geometry={nodes.Plane_2.geometry}
          material={materials["Beige Concrete Shadow"]}
        />
      </group>
      <mesh
        geometry={nodes.Dirty_Plane.geometry}
        material={materials["Dirty Beige"]}
        position={[1.76, -0.13, -1.61]}
        rotation={[0.011, -0.666, 0.006]}
        scale={[1.356, 0.233, 1.356]}
      />
      <mesh
        geometry={nodes.Dirty_Plane002.geometry}
        material={materials["Dirty Beige"]}
        position={[1.568, -0.106, 5.187]}
        rotation={[-3.009, -1.464, -3.018]}
        scale={[1.088, 0.52, 1.088]}
      />
      <mesh
        geometry={nodes.Dirty_Plane003.geometry}
        material={materials["Dirty Beige"]}
        position={[-3.056, -0.115, 1.425]}
        rotation={[0.006, -0.544, 0.004]}
        scale={[1.392, 0.031, 1.391]}
      />
      <mesh
        geometry={nodes.Plane180.geometry}
        material={materials["Brown Steel Grid"]}
        position={[-2.586, -0.042, -1.971]}
        rotation={[-0.137, 1.365, 0.138]}
        scale={[0.02, 0.114, 0.114]}
      />
      <mesh
        geometry={nodes.Plane181.geometry}
        material={materials["Brown Steel Grid"]}
        position={[-5.834, -0.086, 1.889]}
        rotation={[0, -0.048, 0]}
        scale={[0.02, 0.114, 0.114]}
      />
      <mesh
        geometry={nodes.Plane182.geometry}
        material={materials["Brown Steel Grid"]}
        position={[4.301, -0.042, 4.947]}
        rotation={[-0.137, 1.365, 0.138]}
        scale={[0.02, 0.114, 0.114]}
      />
      <mesh
        geometry={nodes.Plane183.geometry}
        material={materials["Brown Steel Grid"]}
        position={[-6.203, -0.008, 4.477]}
        rotation={[2.029, 0.838, -2.13]}
        scale={[0.02, 0.114, 0.114]}
      />
      <mesh
        geometry={nodes.Plane184.geometry}
        material={materials["Brown Steel Grid"]}
        position={[-1.207, -0.066, 5.64]}
        rotation={[2.425, 0.223, -2.947]}
        scale={[0.018, 0.107, 0.107]}
      />
      <mesh
        geometry={nodes.Plane185.geometry}
        material={materials["Brown Steel Grid"]}
        position={[0.985, -0.029, -2.246]}
        rotation={[0, -0.345, 0]}
        scale={[0.02, 0.114, 0.114]}
      />
      <mesh
        geometry={nodes.Plane186.geometry}
        material={materials["Brown Steel Grid"]}
        position={[0.189, -0.081, 5.151]}
        rotation={[0, -0.038, 0]}
        scale={[0.02, 0.114, 0.114]}
      />
      <mesh
        geometry={nodes.Plane187.geometry}
        material={materials["Brown Steel Grid"]}
        position={[0.305, -0.086, -1.525]}
        rotation={[0, -0.502, 0]}
        scale={[0.02, 0.114, 0.114]}
      />
      <mesh
        geometry={nodes.CurlyCurve004.geometry}
        material={materials.Black}
        position={[0.291, -0.067, -1.357]}
        rotation={[0, -0.189, 0]}
        scale={1.755}
      />
      <mesh
        geometry={nodes.CurlyCurve005.geometry}
        material={materials.Black}
        position={[-0.836, -0.067, -1.098]}
        rotation={[0, -0.408, 0]}
        scale={1.755}
      />
      <mesh
        geometry={nodes.CurlyCurve006.geometry}
        material={materials.Black}
        position={[-1.121, -0.067, -1.059]}
        rotation={[0, -0.408, 0]}
        scale={1.755}
      />
      <mesh
        geometry={nodes.CurlyCurve007.geometry}
        material={materials.Black}
        position={[-1.759, -0.067, -0.388]}
        rotation={[0, 0.064, 0]}
        scale={1.755}
      />
      <mesh
        geometry={nodes.CurlyCurve008.geometry}
        material={materials.Black}
        position={[-2.786, -0.067, 0.145]}
        rotation={[0, -0.155, 0]}
        scale={1.755}
      />
      <mesh
        geometry={nodes.CurlyCurve009.geometry}
        material={materials.Black}
        position={[-3.052, -0.067, 0.254]}
        rotation={[0, -0.155, 0]}
        scale={1.755}
      />
      <mesh
        geometry={nodes.CurlyCurve010.geometry}
        material={materials.Black}
        position={[-4.394, -0.067, -2.212]}
        rotation={[0, -0.977, 0]}
        scale={1.755}
      />
      <group
        position={[-24.018, 2.27, 17.372]}
        rotation={[-0.544, -0.05, -0.03]}
        scale={[0.013, 0.698, 0.013]}
      >
        <mesh
          geometry={nodes.Cylinder016.geometry}
          material={materials.Black}
        />
        <mesh
          geometry={nodes.Cylinder016_1.geometry}
          material={materials["Metallic Dark"]}
        />
      </group>
      <group
        position={[-23.914, 1.771, 18.557]}
        rotation={[-0.942, -0.128, 0.047]}
        scale={0.535}
      >
        <mesh
          geometry={nodes.Cone001.geometry}
          material={materials["Red Umbrella"]}
        />
        <mesh
          geometry={nodes.Cone001_1.geometry}
          material={materials["White Table Top"]}
        />
      </group>
      <group
        position={[38.403, 13.958, 11.906]}
        rotation={[1.777, -0.516, 1.545]}
      >
        <mesh
          geometry={nodes.Circle002.geometry}
          material={materials.Metallic}
        />
        <mesh
          geometry={nodes.Circle002_1.geometry}
          material={materials["Middle Black Car"]}
        />
        <mesh
          geometry={nodes.Circle002_2.geometry}
          material={materials["Car Black"]}
        />
        <mesh
          geometry={nodes.Circle002_3.geometry}
          material={materials.White}
        />
        <mesh
          geometry={nodes.Circle002_4.geometry}
          material={materials.Windows}
        />
        <mesh geometry={nodes.Circle002_5.geometry} material={materials.Red} />
        <mesh
          geometry={nodes.Circle002_6.geometry}
          material={materials["White Glow"]}
        />
        <mesh
          geometry={nodes.Circle002_7.geometry}
          material={materials["Orange.001"]}
        />
        <mesh geometry={nodes.Circle002_8.geometry} material={materials.Blue} />
      </group>
      <group
        position={[4.074, 9.886, 26.675]}
        rotation={[2.493, 0.096, -3.129]}
      >
        <mesh
          geometry={nodes.Circle003.geometry}
          material={materials.Metallic}
        />
        <mesh
          geometry={nodes.Circle003_1.geometry}
          material={materials["Middle Black Car"]}
        />
        <mesh
          geometry={nodes.Circle003_2.geometry}
          material={materials["Taxi Color"]}
        />
        <mesh
          geometry={nodes.Circle003_3.geometry}
          material={materials["Taxi Color"]}
        />
        <mesh
          geometry={nodes.Circle003_4.geometry}
          material={materials.Windows}
        />
        <mesh
          geometry={nodes.Circle003_5.geometry}
          material={materials.Black}
        />
        <mesh
          geometry={nodes.Circle003_6.geometry}
          material={materials["White Glow"]}
        />
        <mesh
          geometry={nodes.Circle003_7.geometry}
          material={materials["Metallic Dark"]}
        />
        <mesh geometry={nodes.Circle003_8.geometry} material={materials.Red} />
        <mesh
          geometry={nodes.Circle003_9.geometry}
          material={materials.Orange}
        />
        <mesh
          geometry={nodes.Circle003_10.geometry}
          material={materials.Yellow}
        />
        <mesh
          geometry={nodes.Circle003_11.geometry}
          material={materials["Orange License Plate"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials.Black}
        position={[0, -1.223, 0]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Cardboard}
        position={[2.132, 0.076, -4.218]}
        scale={[0.171, 0.071, 0.119]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials.Cardboard}
        position={[2.518, 0.087, -4.218]}
        rotation={[0, -0.183, 0]}
        scale={[0.136, 0.08, 0.134]}
      />
      <group position={[1.721, -0.085, -4.233]} scale={[0.079, 0.477, 0.184]}>
        <mesh
          geometry={nodes.Cube031.geometry}
          material={materials["Gray Box 1"]}
        />
        <mesh
          geometry={nodes.Cube031_1.geometry}
          material={materials["Gray Box 2"]}
        />
      </group>
      <group
        position={[2.404, -0.205, -4.218]}
        rotation={[0, -0.191, 0]}
        scale={0.364}
      >
        <mesh
          geometry={nodes.Cube032.geometry}
          material={materials["Gray Box 1"]}
        />
        <mesh
          geometry={nodes.Cube032_1.geometry}
          material={materials["Gray Box 2"]}
        />
        <mesh
          geometry={nodes.Cube032_2.geometry}
          material={materials["Gray Box 3"]}
        />
        <mesh
          geometry={nodes.Cube032_3.geometry}
          material={materials["Gray Box 4"]}
        />
        <mesh
          geometry={nodes.Cube032_4.geometry}
          material={materials["Gray Box 5"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials["White Box"]}
        position={[1.999, 0.273, -4.218]}
        scale={[0.098, 0.058, 0.097]}
      />
      <group
        position={[2.382, 0.484, -4.218]}
        rotation={[0, -0.265, 0]}
        scale={[0.174, 0.041, 0.122]}
      >
        <mesh
          geometry={nodes.Cube034.geometry}
          material={materials["White Box"]}
        />
        <mesh
          geometry={nodes.Cube034_1.geometry}
          material={materials["Green Bin"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials.Black}
        position={[1.748, 0.065, -4.218]}
        scale={[0.142, 0.051, 0.146]}
      />
      <group position={[2.132, 0.006, -4.218]} scale={0.284}>
        <mesh
          geometry={nodes.Cube021_1.geometry}
          material={materials["Table Red"]}
        />
        <mesh
          geometry={nodes.Cube021_2.geometry}
          material={materials["White Table Top"]}
        />
      </group>
      <mesh
        geometry={nodes.Plane011.geometry}
        material={materials["Green Bin"]}
        position={[1.751, 0.006, -4.218]}
        scale={0.317}
      />
      <group
        position={[2.552, 0.376, -4.015]}
        rotation={[Math.PI / 2, 0, 0.191]}
        scale={[0.015, 0.015, 0.025]}
      >
        <mesh
          geometry={nodes.Plane247.geometry}
          material={materials["Gray Box 3"]}
        />
        <mesh
          geometry={nodes.Plane247_1.geometry}
          material={materials["Gray Box 4"]}
        />
      </group>
      <group
        position={[2.181, 0.375, -4.088]}
        rotation={[Math.PI / 2, 0, 0.191]}
        scale={[0.015, 0.015, 0.025]}
      >
        <mesh
          geometry={nodes.Plane248.geometry}
          material={materials["Gray Box 3"]}
        />
        <mesh
          geometry={nodes.Plane248_1.geometry}
          material={materials["Gray Box 4"]}
        />
      </group>
      <group
        position={[2.519, 0.659, -4.154]}
        rotation={[Math.PI, -1.161, Math.PI]}
        scale={0.035}
      >
        <mesh geometry={nodes.Cube036.geometry} material={materials.Black} />
        <mesh
          geometry={nodes.Cube036_1.geometry}
          material={materials["Red Screwdriver"]}
        />
      </group>
      <group
        position={[1.835, 0.235, -3.989]}
        rotation={[Math.PI / 2, 0, 1.772]}
        scale={0.013}
      >
        <mesh
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Yellow}
        />
        <mesh
          geometry={nodes.Cylinder001_2.geometry}
          material={materials.Black}
        />
        <mesh
          geometry={nodes.Cylinder001_3.geometry}
          material={materials.Silver}
        />
        <mesh
          geometry={nodes.Cylinder001_4.geometry}
          material={materials.Bronze}
        />
      </group>
      <group
        position={[1.804, 0.235, -3.958]}
        rotation={[Math.PI / 2, 0, 1.999]}
        scale={0.013}
      >
        <mesh
          geometry={nodes.Cylinder002_1.geometry}
          material={materials["Blue Screwdriver"]}
        />
        <mesh
          geometry={nodes.Cylinder002_2.geometry}
          material={materials.Black}
        />
        <mesh
          geometry={nodes.Cylinder002_3.geometry}
          material={materials.Silver}
        />
        <mesh
          geometry={nodes.Cylinder002_4.geometry}
          material={materials.Bronze}
        />
      </group>
      <group
        position={[2.575, 0.662, -3.976]}
        rotation={[Math.PI / 2, 0, 2.084]}
        scale={0.013}
      >
        <mesh
          geometry={nodes.Cylinder003_1.geometry}
          material={materials["Table Red"]}
        />
        <mesh
          geometry={nodes.Cylinder003_2.geometry}
          material={materials.Black}
        />
        <mesh
          geometry={nodes.Cylinder003_3.geometry}
          material={materials.Silver}
        />
        <mesh
          geometry={nodes.Cylinder003_4.geometry}
          material={materials.Bronze}
        />
      </group>
      <group
        position={[2.598, 0.662, -4.025]}
        rotation={[Math.PI / 2, 0, 1.915]}
        scale={0.013}
      >
        <mesh
          geometry={nodes.Cylinder004_1.geometry}
          material={materials.Yellow}
        />
        <mesh
          geometry={nodes.Cylinder004_2.geometry}
          material={materials.Black}
        />
        <mesh
          geometry={nodes.Cylinder004_3.geometry}
          material={materials.Silver}
        />
        <mesh
          geometry={nodes.Cylinder004_4.geometry}
          material={materials.Bronze}
        />
      </group>
      <group
        position={[2.48, 0.693, -4.459]}
        rotation={[0, -0.581, 0]}
        scale={[0.02, 0.01, 0.008]}
      >
        <mesh geometry={nodes.Cube038.geometry} material={materials.White} />
        <mesh
          geometry={nodes.Cube038_1.geometry}
          material={materials["White Glow"]}
        />
      </group>
      <group position={[1.77, 0.829, -4.458]} scale={[0.19, 0.19, 0.072]}>
        <mesh
          geometry={nodes.Cube040.geometry}
          material={materials["Gray Box 1"]}
        />
        <mesh
          geometry={nodes.Cube040_1.geometry}
          material={materials["Red Box 2"]}
        />
        <mesh
          geometry={nodes.Cube040_2.geometry}
          material={materials["Gray Box 3"]}
        />
        <mesh
          geometry={nodes.Cube040_3.geometry}
          material={materials["Red Box"]}
        />
      </group>
      <group
        position={[2.021, 0.852, -4.366]}
        rotation={[0, 0.045, 0]}
        scale={0.006}
      >
        <mesh
          geometry={nodes.Cube044.geometry}
          material={materials["Gray Box 5"]}
        />
        <mesh geometry={nodes.Cube044_1.geometry} material={materials.Black} />
        <mesh
          geometry={nodes.Cube044_2.geometry}
          material={materials["Gray Box 4"]}
        />
        <mesh
          geometry={nodes.Cube044_3.geometry}
          material={materials["Gray Box 1"]}
        />
      </group>
      <mesh
        geometry={nodes.Plane010.geometry}
        material={materials["Dirty Gray"]}
        position={[1.695, 0.652, -4.116]}
        rotation={[0, -0.22, 0]}
        scale={[0.072, 0.072, 0.039]}
      />
      <group
        position={[1.656, 0.66, -4.096]}
        rotation={[Math.PI / 2, 0, -1.35]}
        scale={[0.006, 0.038, 0.006]}
      >
        <mesh
          geometry={nodes.Cylinder014.geometry}
          material={materials["Red Screwdriver"]}
        />
        <mesh
          geometry={nodes.Cylinder014_1.geometry}
          material={materials.Steel}
        />
        <mesh
          geometry={nodes.Cylinder014_2.geometry}
          material={materials.Metallic}
        />
        <mesh
          geometry={nodes.Cylinder014_3.geometry}
          material={materials["Blue Screwdriver"]}
        />
        <mesh
          geometry={nodes.Cylinder014_4.geometry}
          material={materials.Black}
        />
        <mesh
          geometry={nodes.Cylinder014_5.geometry}
          material={materials["Orange Screwdriver"]}
        />
        <mesh
          geometry={nodes.Cylinder014_6.geometry}
          material={materials["Green Bin"]}
        />
      </group>
      <group
        position={[1.672, 0.655, -3.962]}
        rotation={[Math.PI, -1.385, Math.PI]}
        scale={[0.008, 0.028, 0.028]}
      >
        <mesh
          geometry={nodes.Plane252.geometry}
          material={materials.Metallic}
        />
        <mesh
          geometry={nodes.Plane252_1.geometry}
          material={materials["Red Scissors"]}
        />
        <mesh
          geometry={nodes.Plane252_2.geometry}
          material={materials["Gray Box 5"]}
        />
        <mesh geometry={nodes.Plane252_3.geometry} material={materials.Black} />
        <mesh
          geometry={nodes.Plane252_4.geometry}
          material={materials.Yellow}
        />
        <mesh
          geometry={nodes.Plane252_5.geometry}
          material={materials["Metallic Darker"]}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials["Metallic Darker"]}
        position={[2.45, 0.655, -4.002]}
        rotation={[1.636, -0.1, -0.998]}
        scale={[-0.003, -0.016, -0.003]}
      />
      <group
        position={[1.729, 1.021, -4.453]}
        rotation={[-0.007, -0.215, 1.539]}
        scale={[0.006, 0.079, 0.011]}
      >
        <mesh
          geometry={nodes.Cube048.geometry}
          material={materials["Red Scissors"]}
        />
        <mesh geometry={nodes.Cube048_1.geometry} material={materials.Black} />
        <mesh
          geometry={nodes.Cube048_2.geometry}
          material={materials["Metallic Dark"]}
        />
      </group>
      <group
        position={[1.777, 0.635, -4.293]}
        rotation={[0, 0.353, 0]}
        scale={0.046}
      >
        <mesh
          geometry={nodes.Cylinder019.geometry}
          material={materials.Black}
        />
        <mesh
          geometry={nodes.Cylinder019_1.geometry}
          material={materials["Brown Folder"]}
        />
        <mesh
          geometry={nodes.Cylinder019_2.geometry}
          material={materials.Paper}
        />
        <mesh
          geometry={nodes.Cylinder019_3.geometry}
          material={materials["Paper 2"]}
        />
        <mesh
          geometry={nodes.Cylinder019_4.geometry}
          material={materials["Paper 3"]}
        />
        <mesh
          geometry={nodes.Cylinder019_5.geometry}
          material={materials["Paper 4"]}
        />
        <mesh
          geometry={nodes.Cylinder019_6.geometry}
          material={materials["Paper 5"]}
        />
      </group>
      <group
        position={[1.668, 0.653, -4.023]}
        rotation={[0, 0.249, 0]}
        scale={0.024}
      >
        <mesh geometry={nodes.Circle001.geometry} material={materials.Black} />
        <mesh
          geometry={nodes.Circle001_1.geometry}
          material={materials["Brown Folder"]}
        />
        <mesh
          geometry={nodes.Circle001_2.geometry}
          material={materials["Gray Box 5"]}
        />
        <mesh
          geometry={nodes.Circle001_3.geometry}
          material={materials["Gray Box 4"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube022.geometry}
        material={materials["Black.002"]}
        position={[2.138, 0.243, -4.001]}
        scale={[0.163, 0.179, 0.179]}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={materials["Black.002"]}
        position={[2.138, 0.243, -4.001]}
        scale={[0.163, 0.179, 0.179]}
      />
      <mesh
        geometry={nodes.Plane019.geometry}
        material={materials["Black.004"]}
        position={[2.131, 0.277, -4.015]}
        scale={0.167}
      />
      <group
        position={[40.307, 14.729, 6.491]}
        rotation={[1.621, -0.652, 1.604]}
      >
        <mesh
          geometry={nodes.Cube019.geometry}
          material={materials["Beige Concrete Shadow"]}
          position={[0.387, -0.04, -0.894]}
          scale={[0.135, 0.055, 0.135]}
        />
        <mesh
          geometry={nodes.Dirty_Plane001.geometry}
          material={materials["Dirty Beige"]}
          position={[-0.697, -0.073, 1.377]}
          rotation={[-3.009, -1.464, -3.018]}
          scale={[0.852, 0.407, 0.852]}
        />
        <group position={[0.599, 0, -1.493]} scale={2.812}>
          <mesh
            geometry={nodes.Plane254.geometry}
            material={materials["Beige Concrete Shadow"]}
          />
          <mesh
            geometry={nodes.Plane254_1.geometry}
            material={materials["Beige Concrete Base"]}
          />
        </group>
        <mesh
          geometry={nodes.Plane014.geometry}
          material={materials["Brown Steel Grid"]}
          position={[0.26, -0.042, 1.904]}
          rotation={[-0.137, 1.365, 0.138]}
          scale={[0.02, 0.114, 0.114]}
        />
        <group position={[-0.454, -0.003, -0.593]}>
          <mesh
            geometry={nodes.Plane256.geometry}
            material={materials["Beige Concrete Base"]}
          />
          <mesh
            geometry={nodes.Plane256_1.geometry}
            material={materials["Beige Concrete Shadow"]}
          />
        </group>
        <mesh
          geometry={nodes.Plane016.geometry}
          material={materials["Brown Steel Grid"]}
          position={[-2.411, 0.369, 2.767]}
          rotation={[-0.53, -0.33, -0.137]}
          scale={[0.02, 0.114, 0.114]}
        />
      </group>
      <group position={[-0.748, -2.756, 0.038]} scale={[0.928, 0.344, 0.61]}>
        <mesh
          geometry={nodes.Cube055.geometry}
          material={materials["Gray Box 5"]}
        />
        <mesh
          geometry={nodes.Cube055_1.geometry}
          material={materials["Gray Box 1"]}
        />
        <mesh
          geometry={nodes.Cube055_2.geometry}
          material={materials["Gray Box 2"]}
        />
        <mesh geometry={nodes.Cube055_3.geometry} material={materials.Green} />
        <mesh geometry={nodes.Cube055_4.geometry} material={materials.Black} />
        <mesh
          geometry={nodes.Cube055_5.geometry}
          material={materials["White Glow"]}
        />
        <mesh geometry={nodes.Cube055_6.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube055_7.geometry} material={materials.Bronze} />
        <mesh
          geometry={nodes.Cube055_8.geometry}
          material={materials["Dark Bronze"]}
        />
      </group>
      <group
        position={[-1.156, 0.03, -8.422]}
        rotation={[-0.167, -0.001, -0.027]}
        scale={[0.313, 0.116, 0.206]}
      >
        <mesh
          geometry={nodes.Cube062.geometry}
          material={materials["Gray Box 5"]}
        />
        <mesh
          geometry={nodes.Cube062_1.geometry}
          material={materials["Gray Box 1"]}
        />
        <mesh
          geometry={nodes.Cube062_2.geometry}
          material={materials["Gray Box 2"]}
        />
        <mesh geometry={nodes.Cube062_3.geometry} material={materials.Green} />
        <mesh geometry={nodes.Cube062_4.geometry} material={materials.Black} />
        <mesh
          geometry={nodes.Cube062_5.geometry}
          material={materials["White Glow"]}
        />
        <mesh geometry={nodes.Cube062_6.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube062_7.geometry} material={materials.Bronze} />
        <mesh
          geometry={nodes.Cube062_8.geometry}
          material={materials["Dark Bronze"]}
        />
      </group>
      <group
        position={[-4.629, -0.151, -6.881]}
        rotation={[-0.2, 0.307, 0.083]}
        scale={[0.313, 0.116, 0.206]}
      >
        <mesh
          geometry={nodes.Cube065.geometry}
          material={materials["Gray Box 5"]}
        />
        <mesh
          geometry={nodes.Cube065_1.geometry}
          material={materials["Gray Box 1"]}
        />
        <mesh
          geometry={nodes.Cube065_2.geometry}
          material={materials["Gray Box 2"]}
        />
        <mesh geometry={nodes.Cube065_3.geometry} material={materials.Green} />
        <mesh geometry={nodes.Cube065_4.geometry} material={materials.Black} />
        <mesh
          geometry={nodes.Cube065_5.geometry}
          material={materials["White Glow"]}
        />
        <mesh geometry={nodes.Cube065_6.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube065_7.geometry} material={materials.Bronze} />
        <mesh
          geometry={nodes.Cube065_8.geometry}
          material={materials["Dark Bronze"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/venom_platform3.glb");
