/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { Select } from "@react-three/postprocessing";

const Desk = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("/desk.glb");
  const scale = 0.5;
  const [enabled, setHoverEnabled] = useState(false);
  let timeoutId = null;

  const handlePointerOver = (event) => {
    event.stopPropagation();
    if (props.isActualComputerClicked) return;
    if (timeoutId) {
      clearTimeout(timeoutId);
    }
    document.body.style.cursor = "pointer";
    setHoverEnabled(true);
  };

  const handlePointerOut = () => {
    if (timeoutId) {
      clearTimeout(timeoutId);
    }
    timeoutId = setTimeout(() => {
      document.body.style.cursor = "default";
      setHoverEnabled(false);
    }, 10); // delay in milliseconds
  };

  console.log(props.isActualComputerClicked);

  return (
    <Select enabled={enabled && !props.isActualComputerClicked}>
      {/* Mesh that will be looked at */}
      <mesh
        ref={ref}
        {...props}
        position={props.position.map(
          (value, index) => value + [0.031, 0.913, 0.0][index]
        )}
        visible={false}
      >
        <boxGeometry args={[0.5 * scale, 0.33 * scale, 0.05 * scale]} />
        <meshStandardMaterial color="white" />
      </mesh>
      <group
        {...props}
        dispose={null}
        onPointerOver={handlePointerOver}
        onPointerOut={handlePointerOut}
        onClick={(event) => {
          if (!props.isComputerClicked) {
            props.setIsActualComputerClicked(true);
            props.handleMajorMeshClick(
              false,
              0.5,
              1.0,
              ref.current.position,
              ref.current,
              1.5
            );
          }
        }}
      >
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials.Cardboard}
          position={[0.024, 0.069, -0.044]}
          scale={[0.171, 0.071, 0.119]}
        />
        <mesh
          geometry={nodes.Cube001.geometry}
          material={materials.Cardboard}
          position={[0.41, 0.08, -0.044]}
          rotation={[0, -0.183, 0]}
          scale={[0.136, 0.08, 0.134]}
        />
        <group position={[-0.388, -0.092, -0.06]} scale={[0.079, 0.477, 0.184]}>
          <mesh
            geometry={nodes.Cube031.geometry}
            material={materials["Gray Box 1"]}
          />
          <mesh
            geometry={nodes.Cube031_1.geometry}
            material={materials["Gray Box 2"]}
          />
        </group>
        <group
          position={[0.295, -0.212, -0.044]}
          rotation={[0, -0.191, 0]}
          scale={0.364}
        >
          <mesh
            geometry={nodes.Cube032.geometry}
            material={materials["Gray Box 1"]}
          />
          <mesh
            geometry={nodes.Cube032_1.geometry}
            material={materials["Gray Box 2"]}
          />
          <mesh
            geometry={nodes.Cube032_2.geometry}
            material={materials["Gray Box 3"]}
          />
          <mesh
            geometry={nodes.Cube032_3.geometry}
            material={materials["Gray Box 4"]}
          />
          <mesh
            geometry={nodes.Cube032_4.geometry}
            material={materials["Gray Box 5"]}
          />
        </group>
        <mesh
          geometry={nodes.Cube011.geometry}
          material={materials["White Box"]}
          position={[-0.11, 0.266, -0.044]}
          scale={[0.098, 0.058, 0.097]}
        />
        <group
          position={[0.273, 0.477, -0.044]}
          rotation={[0, -0.265, 0]}
          scale={[0.174, 0.041, 0.122]}
        >
          <mesh
            geometry={nodes.Cube034.geometry}
            material={materials["White Box"]}
          />
          <mesh
            geometry={nodes.Cube034_1.geometry}
            material={materials["Green Bin"]}
          />
        </group>
        <mesh
          geometry={nodes.Cube013.geometry}
          material={materials.Black}
          position={[-0.361, 0.058, -0.044]}
          scale={[0.142, 0.051, 0.146]}
        />
        <group position={[0, -0.001, 0]} scale={0.284}>
          <mesh
            geometry={nodes.Cube021_1.geometry}
            material={materials["Table Red"]}
          />
          <mesh
            geometry={nodes.Cube021_2.geometry}
            material={materials["White Table Top"]}
          />
        </group>
        <mesh
          geometry={nodes.Plane011.geometry}
          material={materials["Green Bin"]}
          position={[-0.358, -0.001, -0.044]}
          scale={0.317}
        />
        <group
          position={[0.444, 0.369, 0.158]}
          rotation={[Math.PI / 2, 0, 0.191]}
          scale={[0.015, 0.015, 0.025]}
        >
          <mesh
            geometry={nodes.Plane247.geometry}
            material={materials["Gray Box 3"]}
          />
          <mesh
            geometry={nodes.Plane247_1.geometry}
            material={materials["Gray Box 4"]}
          />
        </group>
        <group
          position={[0.073, 0.368, 0.086]}
          rotation={[Math.PI / 2, 0, 0.191]}
          scale={[0.015, 0.015, 0.025]}
        >
          <mesh
            geometry={nodes.Plane248.geometry}
            material={materials["Gray Box 3"]}
          />
          <mesh
            geometry={nodes.Plane248_1.geometry}
            material={materials["Gray Box 4"]}
          />
        </group>
        <group
          position={[0.41, 0.652, 0.019]}
          rotation={[Math.PI, -1.161, Math.PI]}
          scale={0.035}
        >
          <mesh geometry={nodes.Cube036.geometry} material={materials.Black} />
          <mesh
            geometry={nodes.Cube036_1.geometry}
            material={materials["Red Screwdriver"]}
          />
        </group>
        <group
          position={[-0.273, 0.228, 0.184]}
          rotation={[Math.PI / 2, 0, 1.772]}
          scale={0.013}
        >
          <mesh
            geometry={nodes.Cylinder001_1.geometry}
            material={materials.Yellow}
          />
          <mesh
            geometry={nodes.Cylinder001_2.geometry}
            material={materials.Black}
          />
          <mesh
            geometry={nodes.Cylinder001_3.geometry}
            material={materials.Silver}
          />
          <mesh
            geometry={nodes.Cylinder001_4.geometry}
            material={materials.Bronze}
          />
        </group>
        <group
          position={[-0.304, 0.228, 0.215]}
          rotation={[Math.PI / 2, 0, 1.999]}
          scale={0.013}
        >
          <mesh
            geometry={nodes.Cylinder002_1.geometry}
            material={materials["Blue Screwdriver"]}
          />
          <mesh
            geometry={nodes.Cylinder002_2.geometry}
            material={materials.Black}
          />
          <mesh
            geometry={nodes.Cylinder002_3.geometry}
            material={materials.Silver}
          />
          <mesh
            geometry={nodes.Cylinder002_4.geometry}
            material={materials.Bronze}
          />
        </group>
        <group
          position={[0.467, 0.655, 0.197]}
          rotation={[Math.PI / 2, 0, 2.084]}
          scale={0.013}
        >
          <mesh
            geometry={nodes.Cylinder003_1.geometry}
            material={materials["Table Red"]}
          />
          <mesh
            geometry={nodes.Cylinder003_2.geometry}
            material={materials.Black}
          />
          <mesh
            geometry={nodes.Cylinder003_3.geometry}
            material={materials.Silver}
          />
          <mesh
            geometry={nodes.Cylinder003_4.geometry}
            material={materials.Bronze}
          />
        </group>
        <group
          position={[0.49, 0.655, 0.148]}
          rotation={[Math.PI / 2, 0, 1.915]}
          scale={0.013}
        >
          <mesh
            geometry={nodes.Cylinder004_1.geometry}
            material={materials.Yellow}
          />
          <mesh
            geometry={nodes.Cylinder004_2.geometry}
            material={materials.Black}
          />
          <mesh
            geometry={nodes.Cylinder004_3.geometry}
            material={materials.Silver}
          />
          <mesh
            geometry={nodes.Cylinder004_4.geometry}
            material={materials.Bronze}
          />
        </group>
        <group
          position={[0.371, 0.686, -0.286]}
          rotation={[0, -0.581, 0]}
          scale={[0.02, 0.01, 0.008]}
        >
          <mesh geometry={nodes.Cube038.geometry} material={materials.White} />
          <mesh
            geometry={nodes.Cube038_1.geometry}
            material={materials["White Glow"]}
          />
        </group>
        <group position={[-0.339, 0.822, -0.285]} scale={[0.19, 0.19, 0.072]}>
          <mesh
            geometry={nodes.Cube040.geometry}
            material={materials["Gray Box 1"]}
          />
          <mesh
            geometry={nodes.Cube040_1.geometry}
            material={materials["Red Box 2"]}
          />
          <mesh
            geometry={nodes.Cube040_2.geometry}
            material={materials["Gray Box 3"]}
          />
          <mesh
            geometry={nodes.Cube040_3.geometry}
            material={materials["Red Box"]}
          />
        </group>
        <group
          position={[-0.088, 0.845, -0.193]}
          rotation={[0, 0.045, 0]}
          scale={0.006}
        >
          <mesh
            geometry={nodes.Cube044.geometry}
            material={materials["Gray Box 5"]}
          />
          <mesh
            geometry={nodes.Cube044_1.geometry}
            material={materials.Black}
          />
          <mesh
            geometry={nodes.Cube044_2.geometry}
            material={materials["Gray Box 4"]}
          />
          <mesh
            geometry={nodes.Cube044_3.geometry}
            material={materials["Gray Box 1"]}
          />
        </group>
        <mesh
          geometry={nodes.Plane010.geometry}
          material={materials["Dirty Gray"]}
          position={[-0.413, 0.645, 0.057]}
          rotation={[0, -0.22, 0]}
          scale={[0.072, 0.072, 0.039]}
        />
        <group
          position={[-0.453, 0.653, 0.077]}
          rotation={[Math.PI / 2, 0, -1.35]}
          scale={[0.006, 0.038, 0.006]}
        >
          <mesh
            geometry={nodes.Cylinder014.geometry}
            material={materials["Red Screwdriver"]}
          />
          <mesh
            geometry={nodes.Cylinder014_1.geometry}
            material={materials.Steel}
          />
          <mesh
            geometry={nodes.Cylinder014_2.geometry}
            material={materials.Metallic}
          />
          <mesh
            geometry={nodes.Cylinder014_3.geometry}
            material={materials["Blue Screwdriver"]}
          />
          <mesh
            geometry={nodes.Cylinder014_4.geometry}
            material={materials.Black}
          />
          <mesh
            geometry={nodes.Cylinder014_5.geometry}
            material={materials["Orange Screwdriver"]}
          />
          <mesh
            geometry={nodes.Cylinder014_6.geometry}
            material={materials["Green Bin"]}
          />
        </group>
        <group
          position={[-0.437, 0.648, 0.211]}
          rotation={[Math.PI, -1.385, Math.PI]}
          scale={[0.008, 0.028, 0.028]}
        >
          <mesh
            geometry={nodes.Plane252.geometry}
            material={materials.Metallic}
          />
          <mesh
            geometry={nodes.Plane252_1.geometry}
            material={materials["Red Scissors"]}
          />
          <mesh
            geometry={nodes.Plane252_2.geometry}
            material={materials["Gray Box 5"]}
          />
          <mesh
            geometry={nodes.Plane252_3.geometry}
            material={materials.Black}
          />
          <mesh
            geometry={nodes.Plane252_4.geometry}
            material={materials.Yellow}
          />
          <mesh
            geometry={nodes.Plane252_5.geometry}
            material={materials["Metallic Darker"]}
          />
        </group>
        <mesh
          geometry={nodes.Cylinder005.geometry}
          material={materials["Metallic Darker"]}
          position={[0.341, 0.648, 0.171]}
          rotation={[1.636, -0.1, -0.998]}
          scale={[-0.003, -0.016, -0.003]}
        />
        <group
          position={[-0.379, 1.014, -0.28]}
          rotation={[-0.007, -0.215, 1.539]}
          scale={[0.006, 0.079, 0.011]}
        >
          <mesh
            geometry={nodes.Cube048.geometry}
            material={materials["Red Scissors"]}
          />
          <mesh
            geometry={nodes.Cube048_1.geometry}
            material={materials.Black}
          />
          <mesh
            geometry={nodes.Cube048_2.geometry}
            material={materials["Metallic Dark"]}
          />
        </group>
        <group
          position={[-0.332, 0.628, -0.12]}
          rotation={[0, 0.353, 0]}
          scale={0.046}
        >
          <mesh
            geometry={nodes.Cylinder019.geometry}
            material={materials.Black}
          />
          <mesh
            geometry={nodes.Cylinder019_1.geometry}
            material={materials["Brown Folder"]}
          />
          <mesh
            geometry={nodes.Cylinder019_2.geometry}
            material={materials.Paper}
          />
          <mesh
            geometry={nodes.Cylinder019_3.geometry}
            material={materials["Paper 2"]}
          />
          <mesh
            geometry={nodes.Cylinder019_4.geometry}
            material={materials["Paper 3"]}
          />
          <mesh
            geometry={nodes.Cylinder019_5.geometry}
            material={materials["Paper 4"]}
          />
          <mesh
            geometry={nodes.Cylinder019_6.geometry}
            material={materials["Paper 5"]}
          />
        </group>
        <group
          position={[-0.441, 0.646, 0.15]}
          rotation={[0, 0.249, 0]}
          scale={0.024}
        >
          <mesh
            geometry={nodes.Circle001.geometry}
            material={materials.Black}
          />
          <mesh
            geometry={nodes.Circle001_1.geometry}
            material={materials["Brown Folder"]}
          />
          <mesh
            geometry={nodes.Circle001_2.geometry}
            material={materials["Gray Box 5"]}
          />
          <mesh
            geometry={nodes.Circle001_3.geometry}
            material={materials["Gray Box 4"]}
          />
        </group>
        <mesh
          geometry={nodes.Cube022.geometry}
          material={materials["Black.002"]}
          position={[0.029, 0.236, 0.172]}
          scale={[0.163, 0.179, 0.179]}
        />
        <mesh
          geometry={nodes.Cube023.geometry}
          material={materials["Black.002"]}
          position={[0.029, 0.236, 0.172]}
          scale={[0.163, 0.179, 0.179]}
        />
        <mesh
          geometry={nodes.Plane019.geometry}
          material={materials["Black.004"]}
          position={[0.022, 0.27, 0.158]}
          scale={0.167}
        />
      </group>
    </Select>
  );
});

useGLTF.preload("/desk.glb");

export default Desk;
