/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/animated_spiderman_ps5.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <group name="Spider-Man">
            <skinnedMesh
              name="Spider-Man_Redmesh"
              geometry={nodes["Spider-Man_Redmesh"].geometry}
              material={materials.Red}
              skeleton={nodes["Spider-Man_Redmesh"].skeleton}
            />
            <skinnedMesh
              name="Spider-Man_Redmesh_1"
              geometry={nodes["Spider-Man_Redmesh_1"].geometry}
              material={materials.Blue}
              skeleton={nodes["Spider-Man_Redmesh_1"].skeleton}
            />
            <skinnedMesh
              name="Spider-Man_Redmesh_2"
              geometry={nodes["Spider-Man_Redmesh_2"].geometry}
              material={materials.Black}
              skeleton={nodes["Spider-Man_Redmesh_2"].skeleton}
            />
            <skinnedMesh
              name="Spider-Man_Redmesh_3"
              geometry={nodes["Spider-Man_Redmesh_3"].geometry}
              material={materials.White}
              skeleton={nodes["Spider-Man_Redmesh_3"].skeleton}
            />
          </group>
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/animated_spiderman_ps5.glb");
